### ISSUE TITLE
Memory cap when running in a docker container

### ISSUE THREAD

**Issue by igrayson** [pganalyze/pganalyze-collector#11]
Hello,

What is the lowest memory limit we can safely apply to the collector when running in a docker container?

We initially tried with 64mb, which it exceeded after a few days of operation.

**Comment by lfittl** [comment]
Hi @igrayson,

It depends a bit on the size and complexity of the statements being monitored.

For now we default to 256mb in our systemd configuration (https://github.com/pganalyze/collector/blob/master/contrib/systemd/pganalyze-collector.service) so thats probably a good limit for the Docker container as well.

Also to make sure, this repository is outdated (and we'll archive it soon), the correct one is https://github.com/pganalyze/collector

I'll close this issue for now, but please open a new issue in the other repo in case the higher limit still causes issues.
