### ISSUE TITLE
how to find correct value for PGA_API_KEY

### ISSUE THREAD

**Issue by sksajid7** [pganalyze/pganalyze-collector#3]
Thanks for the wonderful tool.

Need some help on understanding PGA_API_KEY paramenter

Thanks,
Sajid.

**Comment by sksajid7** [comment]
After signing up to pganalyze.com i was able to get API_KEY.

**Comment by lfittl** [comment]
Yes, sorry if this was confusing - in order to use the collector you need a pganalyze account.
