### ISSUE TITLE
No system information collected

### ISSUE THREAD

**Issue by teohhanhui** [pganalyze/pganalyze-collector#9]
Under https://github.com/pganalyze/pganalyze-collector/blob/77b4762b05d37f0a65c890af4c90e2eafbb60c35/README.md#docker-sidekick-service it says:

> Note: You can add -v /path/to/database/volume/on/host:/var/lib/postgresql/data in order to collect I/O statistics from your database, this requires that it runs on the same machine.

But I've done exactly that (substituting for the correct path, of course) and it doesn't work. Also, no system information shows up under the Server tab.

**Comment by teohhanhui** [comment]
As far as I can tell, my set-up should pass the `is_remote_system()` test here: https://github.com/pganalyze/pganalyze-collector/blob/d32b7495c08201101d091061b5997dc2f3206e6a/pganalyze-collector.py#L40

**Comment by teohhanhui** [comment]
Oops... This is the old repo. Sorry...

**Comment by lfittl** [comment]
No worries :)
